id: create_a_safety_net
learningObjectives: 
- Implementing a 404 page to catch any broken links or missing pages.
hints:
- Create a new component that let users know that the page they are trying to visit does not exist.
- Use react-router-dom to handle 404 page.
startFlow:
  do:
  - actionId: bot_message
    params:
      person: lucca
      messages:
      - text: "Great work in identifying the issue! Now that we know it's a missing page, we need to create a 404 page to handle any broken links or missing pages in the future."
        delay: 1300
      - text: "In the 404 page you can add the text as _Oops, Looks like you've stumbled upon a item that currently does not exist. But don't worry, there are plenty of other cool items to choose from in the Anythink marketplace. Take a look around and find something new!_ "
        delay: 1400
      - text: "Once you create this component, add it to the routing and create a PR."
        delay: 3500
trigger: 
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
          - actionId: bot_message
            params:
              person: lucca
              messages:
              - text: "On it, I'll review the changes right away."
                delay: 1000
          - actionId: github_pr_comment
            params:
              person: lucca
              message: "On it, I'll review the changes right away."
        github_pr_workflow_complete_success:
          do:
          - actionId: bot_message
            params:
              person: lucca
              messages:
              - text: "Great job! Your attention to detail have ensured that our customers will never be lost again. Keep up the good work. Go ahead and merge the PR."
                delay: 2000
          - actionId: github_pr_approve
            params:
              person: lucca
              message: "Great job! Your attention to detail have ensured that our customers will never be lost again. Keep up the good work. Go ahead and merge the PR."
        github_pr_workflow_complete_failure:
          do:
          - actionId: bot_message
            params:
              person: lucca
              messages:
              - text: "Oh no! It looks like there might be an issue with your implementation. Can you take a look troubleshoot to get it working correctly?"
                delay: 3000
          - actionId: github_pr_reject
            params:
              person: lucca
              message: "Oh no! It looks like there might be an issue with your implementation. Can you take a look troubleshoot to get it working correctly?"
        github_pr_merged:
          do:
          - actionId: finish_step
githubActions:
  backend:
  frontend:
    capabilities:
    - enzyme
    testFile: "route.test.js"