id: uncovering_the_mystery
learningObjectives: 
- Identifying root cause of issue. This will involve debugging the code and conducting thorough research to pinpoint the exact location of the problem.
hints:
- Check if there is any error in console or the app is running properly. 
- Find if routing is properly configued for that page.
startFlow:
  do:
  - actionId: bot_message
    params:
      person: lucca
      messages:
      - text: "Hey there! My name is Lucca and I work with Vanessa and Navi at Anythink. I'm really excited to be working with you on this project."
        delay: 2000
      - text: "Well, we've been getting a lot of complaints from our customers that they're landing on a blank page when they try to access the **/product** route. It's really important that we figure out what's causing this issue so we can fix it as soon as possible."
        delay: 3500
      - text: "Can you please take a look and see if you can find the root cause of the issue? Check the console, or any error messages in the code, or other possibilities."
        delay: 2500
      - text: "Let me know what the issue is once you've identified it, so that we can work on a solution."
        delay: 2000
trigger:
  type: user_message
  params: 
    person: lucca
  flowNode:
    if:
      conditions:
      - conditionId: text_match_regex
        params:
          text: "${userMessageText}"
          regex: routing configuration|missing page|404|page not found|route configuration|broken link
          flags: i
      then:
        do:
        - actionId: bot_message
          params:
            person: lucca
            messages:
            - text: Great job! You've successfully identified the issue. We can move forward and work on a solution.
              delay: 1300
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: lucca
            messages:
            - text: It seems like you're still not quite sure what the issue is. We understand that debugging can be challenging, but don't worry, we're here to help.
              delay: 1000
            - text:  Can you please take another look and let us know if you need any assistance.
              delay: 1000
